# Generated by Django 3.2.8 on 2022-04-26 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20220426_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SUser',
        ),
    ]
