# Generated by Django 4.0.4 on 2022-05-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_adminwallet_btn_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('credit', 'credit'), ('processing', 'processing'), ('confirming', 'confirming'), ('processed', 'processed'), ('error', 'error'), ('server error', 'server error')], max_length=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(default='00.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bonus',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='btn_address',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
