# Generated by Django 4.0.4 on 2022-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_country_profile_gender_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/profile-image-placeholder.png', upload_to='profile-image/%h/%Y/'),
        ),
    ]
