# Generated by Django 4.0.4 on 2022-05-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_transaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deposit_before',
            field=models.BooleanField(default=False),
        ),
    ]
