# Generated by Django 4.0.4 on 2022-05-09 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0022_profile_deposit_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='refers',
            field=models.ManyToManyField(related_name='refers', to=settings.AUTH_USER_MODEL),
        ),
    ]
