# Generated by Django 4.0.4 on 2022-05-09 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0024_profile_refer_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refer_clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='refers',
            field=models.ManyToManyField(blank=True, related_name='refers', to=settings.AUTH_USER_MODEL),
        ),
    ]
