# Generated by Django 4.0.4 on 2022-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_refer_clicks_alter_profile_refers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='refer_clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
