# Generated by Django 4.0.4 on 2022-05-09 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_wallet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='btn_address',
            new_name='btc_address',
        ),
    ]
