# Generated by Django 4.0.4 on 2022-05-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_rename_btn_address_wallet_btc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
