# Generated by Django 4.0.4 on 2022-05-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_profile_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash_id',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
