# Generated by Django 4.0.4 on 2022-05-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_transaction_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('credit', 'credit'), ('processing', 'processing'), ('confirming', 'confirming'), ('error', 'error'), ('failed', 'failed')], max_length=15),
        ),
    ]
