# Generated by Django 4.0.4 on 2022-05-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash_id',
            field=models.CharField(blank=True, max_length=17, unique=True),
        ),
    ]
