# Generated by Django 4.0.4 on 2022-05-12 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_transaction_hash_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminwallet',
            old_name='btn_address',
            new_name='btc_address',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.CharField(blank=True, default='00.00', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bonus',
            field=models.CharField(blank=True, default='0', max_length=10),
        ),
        migrations.CreateModel(
            name='AdminTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('btc_address', models.TextField(unique=True)),
                ('msg', models.TextField(blank=True)),
                ('transactionId', models.CharField(blank=True, max_length=17)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.wallet')),
            ],
        ),
    ]
