# Generated by Django 4.0.4 on 2022-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_btn_address_adminwallet_btc_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminwallet',
            name='returns',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
