# Generated by Django 4.0.4 on 2022-05-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_adminwallet_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransaction',
            name='plan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
